### PR TITLE
add source to pc and pp

### LINKED ISSUE #27: Missing source in PP and PC triggers test failure in admiral PR test
CleanShot 2022-04-07 at 18 17 37@2x

### PR DESCRIPTION
**Pull request by RealSlimMahdi**
close #27

### CODE REVIEW

**Comment by rossfarrugia** [comment]
@RealSlimMahdi we're planning a merge to main soon for admiraltest so that we can re-send to CRAN, as we renamed the package to remove the dot and it caused downstream dependency issues. is this one ready for review? if so tag me as reviewer and will merge.

**Comment by RealSlimMahdi** [comment]
Hi @millerg23, since Ross and Thomas are on vacation, do you this could be merged with dev at least? @koegerr suggested me to tag you :)

**Review by millerg23 — APPROVED** [review]
Changes look OK to me.

**Comment by millerg23** [comment]
I have approved changes, but I can't see option to merge to DEVEL, not sure if I have correct write permissions to MERGE. @koegerr can you see who can merge ?

**Review by rossfarrugia — APPROVED** [review]

**Comment by rossfarrugia** [comment]
@RealSlimMahdi now merged, sorry for the delay with all the easter holidays.

**Comment by RealSlimMahdi** [comment]
np @rossfarrugia I hope you enjoyed !

**Pull request merged**
