### PR TITLE
#32-Updated `R/get_terms.R`

### PR DESCRIPTION
**Pull request by sophie-gem**
Hi,

(To give a bit of background: I created this issue because this was one section I forgot to update and as a result - when I try to run devtools::document() on my current admiral branch it fails)

What I have done:
- updated the script `R/get_terms.R` as per the linked issue
- run `devtools::document()` to update the documentation
- run `devtools::check()` to make sure nothing was breaking as a result

Let me know if there is anything else required.

Many thanks!

### CODE REVIEW

**Comment by bms63** [comment]
I think I'm a little confused about this update.  Is this admiral_smq_db already created in admiral and this function is looking for that data? 

@thomas-neitmann do you agree with this change

**Comment by sophie-gem** [comment]
> I think I'm a little confused about this update. Is this admiral_smq_db already created in admiral and this function is looking for that data?
> 
> @thomas-neitmann do you agree with this change

@bms63 - `admiral_smq_db` and `admiral_sdq_db` are both datasets created in `admiraltest` and the `get_terms.R` script creates an example function to use within the `admiral::create_query_data()` function. The `roxygen2` examples within `create_query_data.R` call this example function and within this function these datasets are called. I don't know if that helps with understanding at all?

**Comment by bms63** [comment]
Sorry...I guess I understood this update to be only datasets that are commonly named.  For example, everyone is probably going to have adsl in a script or at least at the end.  Renaming our datasets to admiral_adsl helps to ensure this doesn't impact a user's code.  Does everyone have a smq dataset?

Is this just to help us stay consistent with our naming conventions for datasets that exist in our packages?  @bundfussr  or @thomas-neitmann  any thoughts.  I have no issue with this update.  I just haven't worked on the smq or sdq stuff so just nervous to make an udpate.

**Comment by sophie-gem** [comment]
Very sorry if I have misunderstood and caused confusion...

**Comment by bms63** [comment]
Haha no issues.  I'm the slow one in this group...just takes me a while to understand things.  Let's see if others are okay.  I'm fine with this change.

**Comment by bundfussr** [comment]
I think the change is OK.

**Review by bms63 — APPROVED** [review]

**Review by bundfussr — APPROVED** [review]

**Pull request merged**
